# -*- coding: utf-8 -*-
"""manipulasi string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXtq8FNS-2_7bV8UKz3-CJzSKsUXQjQ7

**String**
"""

nama = 'Nabila Zakia Ilmi'
Asal = "indonesia"

print(nama)

print(Asal)

"""MANIPULASI STRING"""

print('halo, nama saya ', nama)

print('halo, nama saya',nama, "asal saya dari", Asal)

"""string + non string"""

ngasal_kota = 'bandar lampung'
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

