# -*- coding: utf-8 -*-
"""Pertemuan3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIgyUbGusHPbFYeLDlCC4y4mk3xsFsio

**Operator in pada String**
"""

berita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan \
teks editor masa kini seperti Visual Studio Code, \
atom, sublime text, dan lain sebagainya.'

print('sublime text' in berita)
print('notepad++' in berita)

"""**Mengakses Karakter dengan Index**"""

nama = 'Lendis Fabri'

print(nama[4])
print(nama[7])
print(nama[-1])
print(nama[-3])

"""**Slicing String**"""

judul = 'Pelajaran Matematika Untuk SD'

print(judul[0:5])
print(judul[:10])
print(judul[10:15])
print(judul[-1:-3])  # output: (kosong karena salah arah slicing)
print(judul[:-3])
print(judul[-5:])

"""**Menghitung Panjang String dengan len()**"""

print(len('Indonesia'))
print(len('Malaysia'))

"""**Mengecek Awalan String startswith()**"""

nomor_telepon_1 = '0871122334455'
nomor_telepon_2 = '6288776655300'
nomor_telepon_3 = '+6233003300330'

kode_negara = '+62'

print(nomor_telepon_1.startswith(kode_negara))
print(nomor_telepon_2.startswith(kode_negara))
print(nomor_telepon_3.startswith(kode_negara))

"""**Mengecek Akhiran String endswith()**"""

email_1 = 'presiden@gmail.com'
email_2 = 'presiden@outlook.com'

print(email_1.endswith('gmail.com'))
print(email_2.endswith('gmail.com'))